name: varSecretsWorkflow
env: 
  WORKFLOW_VAR: "I'm a workflow variable"
on: 
  workflow_dispatch:

jobs:
 varjob:
  runs-on: ubuntu-latest
  env: 
    JOB_VAR: "I'm a JOB_VAR variable"
  steps:
    - name: environment variables
      shell: bash
      env: 
        STEP_VAR: "I'm a STEP_VAR variable."
      run: |
        echo $WORKFLOW_VAR
        echo $JOB_VAR
        echo $STEP_VAR
        echo "The following is a secret: ${{ secrets.SOME_SECRET }}, of course, I cant tell you because then it wouldnt be a secret..."
        echo "The following are default environment variables:"
        echo $GITHUB_ACTOR
        echo $GITHUB_JOB
        echo $GITHUB_REF  
      
  
  
  
